### ISSUE TITLE
ERGO: TRM doesn't work

### ISSUE THREAD

**Issue by Censseo** [oliverw/miningcore#1306] opened 2022-07-09 13:06 UTC
With  TRM v 0.10.2, on MC v70, no SSL, get this error:
![image](https://user-images.githubusercontent.com/3895982/178107021-9465b284-fc21-4000-a109-a28b05b14058.png)
Tried to bypass with --pool_broken_rpc but no effect.

**Comment by oliverw** [comment] 2022-07-09 13:38
Duplicate of #1217

**Closed by oliverw** 2022-07-09 13:38 UTC
Labels: bug

**Comment by Censseo** [comment] 2022-07-09 15:06
So no solution?
