### ISSUE TITLE
how add raven KawPow in miningcore

### ISSUE THREAD

**Issue by xsiroxcoin** [oliverw/miningcore#1174] opened 2022-02-24 13:35 UTC
how add raven KawPow in miningcore can some one post here

**Comment by seperatis** [comment] 2022-03-06 11:18
@xsiroxcoin please, close this issue. 

It's Not a bug, but rather a feature request and it's already in the Discussions thread on the 2nd page.

Feel free to join the Discussion that's already open on the Discussions tab (2nd page) about this feature request.

Thanks

**Closed** 2022-03-07 05:43 UTC
