### ISSUE TITLE
How to block IP address?

### ISSUE THREAD

**Issue by konstiantyn** [oliverw/miningcore#1073] opened 2022-01-07 15:05 UTC
[2022-01-07 14:41:13.5923] [I] [eth] Broadcasting job
[2022-01-07 14:41:13.9855] [I] [eth] [0HMDO1OVTA1ED] Accepting connection from ::ffff:194.8.203.190:58030 ...
[2022-01-07 14:41:13.9855] [I] [eth] [0HMDO1OVTA1ED] Connection from ::ffff:194.8.203.190:58030 accepted on port 3092
[2022-01-07 14:41:13.9912] [I] [eth] [0HMDO1OVTA1EE] Accepting connection from ::ffff:87.79.81.73:42038 ...
[2022-01-07 14:41:13.9912] [I] [eth] [0HMDO1OVTA1EE] Connection from ::ffff:87.79.81.73:42038 accepted on port 3092
[2022-01-07 14:41:14.0469] [I] [eth] [0HMDO1OVTA1EF] Accepting connection from ::ffff:194.8.203.190:57314 ...
[2022-01-07 14:41:14.0469] [I] [eth] [0HMDO1OVTA1EF] Connection from ::ffff:194.8.203.190:57314 accepted on port 3092
[2022-01-07 14:41:14.1820] [I] [zec] [0HMDO1OVS7NJF] Share accepted: D=900
[2022-01-07 14:41:14.2645] [I] [eth] [0HMDO1OVTA1E0] Booting zombie-worker (post-connect silence)
[2022-01-07 14:41:14.2645] [I] [eth] [0HMDO1OVTA1E0] Connection closed
[2022-01-07 14:41:14.3044] [I] [zec] [0HMDO1OVS7NJG] Share accepted: D=750
[2022-01-07 14:41:14.3169] [I] [eth] [0HMDO1OVTA1EG] Accepting connection from ::ffff:194.8.203.190:45010 ...
[2022-01-07 14:41:14.3169] [I] [eth] [0HMDO1OVTA1EG] Connection from ::ffff:194.8.203.190:45010 accepted on port 3092
[2022-01-07 14:41:14.3741] [I] [eth] [0HMDO1OVTA1E1] Booting zombie-worker (post-connect silence)
[2022-01-07 14:41:14.3741] [I] [eth] [0HMDO1OVTA1E1] Connection closed
[2022-01-07 14:41:14.6302] [I] [eth] [0HMDO1OVTA1EH] Accepting connection from ::ffff:24.42.31.197:51885 ...
[2022-01-07 14:41:14.6302] [I] [eth] [0HMDO1OVTA1EH] Connection from ::ffff:24.42.31.197:51885 accepted on port 3092
[2022-01-07 14:41:14.6302] [I] [eth] [0HMDO1OVTA1EI] Accepting connection from ::ffff:87.79.81.73:58344 ...
[2022-01-07 14:41:14.6302] [I] [eth] [0HMDO1OVTA1EI] Connection from ::ffff:87.79.81.73:58344 accepted on port 3092
[2022-01-07 14:41:14.6591] [I] [eth] [0HMDO1OVT56BB] Share accepted: D=0.868
[2022-01-07 14:41:14.7843] [I] [eth] [0HMDO1OVTA1EH] Connection closed
[2022-01-07 14:41:14.8073] [I] [eth] [0HMDO1OVTA1E2] Booting zombie-worker (post-connect silence)
[2022-01-07 14:41:14.8073] [I] [eth] [0HMDO1OVTA1E2] Connection closed
[2022-01-07 14:41:14.8464] [I] [eth] [0HMDO1OVT56AT] Share accepted: D=0.847
[2022-01-07 14:41:14.8464] [I] [eth] [0HMDO1OVT56AJ] Share accepted: D=2.276
[2022-01-07 14:41:14.9696] [I] [eth] [0HMDO1OVT56B4] Share accepted: D=2.626
[2022-01-07 14:41:15.0133] [I] [eth] [0HMDO1OVT56B9] Share rejected: low difficulty share (6.984919309616089E-10) [innominer/a10-1.1.0]

It seems these miniers keep trying to connect and steal shares.
Looking at the log it keeps trying to connect.

**Comment by seperatis** [comment] 2022-01-07 15:41
This is not a bug.

Use your server's firewall to block any IP address you want.

**Comment by oliverw** [comment] 2022-01-07 15:44
Those are not miners. Probably script kiddies or other systems trying to connect to old IPs now assigned to your server.

**Comment by oliverw** [comment] 2022-01-25 12:15
Please don't file infrastructure problems as issues with the software.

**Closed** 2022-01-25 12:14 UTC
